
apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: user-service
build:
  artifacts:
  - image: registry.projectdw.de/syse-usermanager
    context: .
    jib:
      project: de.projectdw:UserManager
      args:
      - -DskipTests
      type: maven
deploy:
  kubectl:
    manifests:
    - kubernetes/service/deployment.yaml
